language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=bnp
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="true"
      NUMPY_VERSION="1.11.2" SCIPY_VERSION="0.18.1" CYTHON_VERSION="0.21"
    - DISTRIB="conda" PYTHON_VERSION="3.6"
      NUMPY_VERSION="1.13.3" SCIPY_VERSION="0.19.1" CYTHON_VERSION="0.27.3"

install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh
