version: 2

jobs:
  python3:
    docker:
      - image: circleci/python:3.6.1
    environment:
      - MINICONDA_PATH: ~/miniconda
      - CONDA_ENV_NAME: testenv
      - PYTHON_VERSION: 3
    steps:
      - checkout
      - restore_cache:
          key: v1-datasets-{{ .Branch }}
      - run: ./ci_scripts/circleci/build_doc.sh
      - save_cache:
          key: v1-datasets-{{ .Branch }}
      - store_artifacts:
          path: doc/_build/html
          destination: doc
      - store_artifacts:
          path: ~/log.txt
          destination: log.txt
      # Persists generated documentation so that it can be attached and deployed
      # in the 'deploy' step.
      - persist_to_workspace:
          root: doc/_build/html
          paths: .
    branches:
      ignore:
        - gh-pages

  deploy:
    docker:
      - image: circleci/python:3.6.1
    environment:
      - USERNAME: "chyikwei"
      - DOC_REPO: "bnp"
      - EMAIL: "chyikwei.yau@gmail.com"
    steps:
      - checkout
      # Attach documentation generated in the 'python3' step so that it can be
      # deployed.
      - attach_workspace:
          at: doc/_build/html
      - run: ls -ltrh doc/_build/html
      - run: bash ci_scripts/circleci/push_doc.sh doc/_build/html
    branches:
      only:
        - master

workflows:
  version: 2
  build-doc-and-deploy:
    jobs:
      - python3
      - deploy:
          requires:
            - python3

  branches:
      ignore:
        - gh-pages
